import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Silk Path | Notifications',
    description: 'Generated by create next app',
  }

export default async function NotificationsLayout({
    children
}: {
    children: React.ReactNode
}) {

    return (
        <div className="mx-10 mt-[50px]">
          {children}
        </div>
    )
}