import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/sidebar/Sidebar'
import ModalProvider from '@/providers/ModalProvider'
import { Toaster } from '@/components/ui/toaster'
import getCurrentUser from '@/actions/getCurrentUser'
import AuthProvider from '@/providers/AuthProvider'
import getFriends from '@/actions/getFriends'
import getUsers from '@/actions/getUsers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Silk Path',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 const currentUser = await getCurrentUser()
 const friends = await getFriends()
 const users = await getUsers()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <ModalProvider friends={friends} currentUser={currentUser} users={users}/>
        <Navbar/>
        <main className='flex flex-row'>
        <Sidebar currentUser={currentUser}/>
        <section className='md:ml-[220px] mt-[100px]'>
        {children}
        <Toaster/>
        </section>
        </main>
        </AuthProvider>
      </body>
    </html>
  )
}
