import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/sidebar/Sidebar'
import ModalProvider from '@/providers/ModalProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Silk Path',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider/>
        <Navbar/>
        <main className='flex flex-row'>
        <Sidebar/>
        <section className='flex min-h-screen flex-1 flex-col items-center bg-black px-6 pb-10 pt-28 sm:px-10'>
        {children}
        </section>
        </main>
      </body>
    </html>
  )
}
