import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Silk Path | Profile',
    description: 'Generated by create next app',
  }

export default async function ProfileLayout({
    children
}: {
    children: React.ReactNode
}) {

    return (
        <div>
          {children}
        </div>
    )
}